[theme]
base = "light"
primaryColor = "#E49B32"
backgroundColor = "#F7F5F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#24313A"
font = "sans-serif"
baseRadius = "large"
buttonRadius = "large"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#234058"
secondaryBackgroundColor = "#355972"
textColor = "#FFFFFF"
